<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IXADFgG' shared service.

return $this->privates['.service_locator.IXADFgG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'jobApplication' => ['privates', '.errored..service_locator.IXADFgG.App\\Entity\\JobApplication', NULL, 'Cannot autowire service ".service_locator.IXADFgG": it references class "App\\Entity\\JobApplication" but no such service exists.'],
], [
    'jobApplication' => 'App\\Entity\\JobApplication',
]);
