<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Candidate extends \App\Entity\Candidate implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'lastName', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'nationality', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'passport', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'curriculum', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'availability', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'birthDate', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'birthLocation', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'experience', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'notes', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'files', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'jobApplications'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'firstName', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'lastName', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'adress', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'nationality', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'passport', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'curriculum', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'picture', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'availability', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'birthDate', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'birthLocation', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'experience', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'notes', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'files', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'user', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Candidate' . "\0" . 'jobApplications'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Candidate $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender(string $gender): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName(string $firstName): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName(string $lastName): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdress', []);

        return parent::getAdress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdress(?string $adress): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdress', [$adress]);

        return parent::setAdress($adress);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(?string $country): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationality(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationality', []);

        return parent::getNationality();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationality(?string $nationality): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationality', [$nationality]);

        return parent::setNationality($nationality);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassport(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassport', []);

        return parent::getPassport();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassport(?string $passport): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassport', [$passport]);

        return parent::setPassport($passport);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurriculum(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurriculum', []);

        return parent::getCurriculum();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurriculum(?string $curriculum): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurriculum', [$curriculum]);

        return parent::setCurriculum($curriculum);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', []);

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture(?string $picture): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', [$picture]);

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailability(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailability', []);

        return parent::getAvailability();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailability(bool $availability): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailability', [$availability]);

        return parent::setAvailability($availability);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthDate', []);

        return parent::getBirthDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthDate(?\DateTimeInterface $birthDate): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthDate', [$birthDate]);

        return parent::setBirthDate($birthDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthLocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthLocation', []);

        return parent::getBirthLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthLocation(?string $birthLocation): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthLocation', [$birthLocation]);

        return parent::setBirthLocation($birthLocation);
    }

    /**
     * {@inheritDoc}
     */
    public function getExperience(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExperience', []);

        return parent::getExperience();
    }

    /**
     * {@inheritDoc}
     */
    public function setExperience(?string $experience): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExperience', [$experience]);

        return parent::setExperience($experience);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', []);

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes(?string $notes): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', [$notes]);

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', []);

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiles(?string $files): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiles', [$files]);

        return parent::setFiles($files);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(?\App\Entity\User $user): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?\App\Entity\Category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(?\App\Entity\Category $category): \App\Entity\Candidate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getJobs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobs', []);

        return parent::getJobs();
    }

}
