<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GUafcmK' shared service.

return $this->privates['.service_locator.GUafcmK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'candidate' => ['privates', '.errored..service_locator.GUafcmK.App\\Entity\\Candidate', NULL, 'Cannot autowire service ".service_locator.GUafcmK": it references class "App\\Entity\\Candidate" but no such service exists.'],
], [
    'candidate' => 'App\\Entity\\Candidate',
]);
