<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Ce9YSx8' shared service.

return $this->privates['.service_locator.Ce9YSx8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'offer' => ['privates', '.errored..service_locator.Ce9YSx8.App\\Entity\\Offer', NULL, 'Cannot autowire service ".service_locator.Ce9YSx8": it references class "App\\Entity\\Offer" but no such service exists.'],
], [
    'offer' => 'App\\Entity\\Offer',
]);
