<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP2Wcn7B\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP2Wcn7B/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP2Wcn7B.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP2Wcn7B\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerP2Wcn7B\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'P2Wcn7B',
    'container.build_id' => 'c909d4c8',
    'container.build_time' => 1563452403,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP2Wcn7B');
